using FluentValidation;
namespace BusinessCloud.Application.Bazares.Queries.GetDeliveryLogisticsEvents;
public class GetDeliveryLogisticsEventsValidator : AbstractValidator<GetDeliveryLogisticsEventsQuery> { }